# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wensheng/helloworld/ES_PHPX

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wensheng/helloworld/ES_PHPX

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wensheng/helloworld/ES_PHPX/CMakeFiles /Users/wensheng/helloworld/ES_PHPX/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wensheng/helloworld/ES_PHPX/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phpx

# Build rule for target.
phpx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phpx
.PHONY : phpx

# fast build rule for target.
phpx/fast:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/build
.PHONY : phpx/fast

# target to build an object file
src/array.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/array.o
.PHONY : src/array.o

# target to preprocess a source file
src/array.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/array.i
.PHONY : src/array.i

# target to generate assembly for a file
src/array.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/array.s
.PHONY : src/array.s

# target to build an object file
src/base.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/base.o
.PHONY : src/base.o

# target to preprocess a source file
src/base.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/base.i
.PHONY : src/base.i

# target to generate assembly for a file
src/base.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/base.s
.PHONY : src/base.s

# target to build an object file
src/class.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/class.o
.PHONY : src/class.o

# target to preprocess a source file
src/class.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/class.i
.PHONY : src/class.i

# target to generate assembly for a file
src/class.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/class.s
.PHONY : src/class.s

# target to build an object file
src/exec.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/exec.o
.PHONY : src/exec.o

# target to preprocess a source file
src/exec.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/exec.i
.PHONY : src/exec.i

# target to generate assembly for a file
src/exec.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/exec.s
.PHONY : src/exec.s

# target to build an object file
src/extension.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/extension.o
.PHONY : src/extension.o

# target to preprocess a source file
src/extension.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/extension.i
.PHONY : src/extension.i

# target to generate assembly for a file
src/extension.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/extension.s
.PHONY : src/extension.s

# target to build an object file
src/function.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/function.o
.PHONY : src/function.o

# target to preprocess a source file
src/function.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/function.i
.PHONY : src/function.i

# target to generate assembly for a file
src/function.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/function.s
.PHONY : src/function.s

# target to build an object file
src/hash.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/hash.o
.PHONY : src/hash.o

# target to preprocess a source file
src/hash.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/hash.i
.PHONY : src/hash.i

# target to generate assembly for a file
src/hash.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/hash.s
.PHONY : src/hash.s

# target to build an object file
src/object.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/object.o
.PHONY : src/object.o

# target to preprocess a source file
src/object.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/object.i
.PHONY : src/object.i

# target to generate assembly for a file
src/object.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/object.s
.PHONY : src/object.s

# target to build an object file
src/string.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/string.o
.PHONY : src/string.o

# target to preprocess a source file
src/string.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/string.i
.PHONY : src/string.i

# target to generate assembly for a file
src/string.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/string.s
.PHONY : src/string.s

# target to build an object file
src/variant.o:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/variant.o
.PHONY : src/variant.o

# target to preprocess a source file
src/variant.i:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/variant.i
.PHONY : src/variant.i

# target to generate assembly for a file
src/variant.s:
	$(MAKE) -f CMakeFiles/phpx.dir/build.make CMakeFiles/phpx.dir/src/variant.s
.PHONY : src/variant.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... phpx"
	@echo "... src/array.o"
	@echo "... src/array.i"
	@echo "... src/array.s"
	@echo "... src/base.o"
	@echo "... src/base.i"
	@echo "... src/base.s"
	@echo "... src/class.o"
	@echo "... src/class.i"
	@echo "... src/class.s"
	@echo "... src/exec.o"
	@echo "... src/exec.i"
	@echo "... src/exec.s"
	@echo "... src/extension.o"
	@echo "... src/extension.i"
	@echo "... src/extension.s"
	@echo "... src/function.o"
	@echo "... src/function.i"
	@echo "... src/function.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/object.o"
	@echo "... src/object.i"
	@echo "... src/object.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
	@echo "... src/variant.o"
	@echo "... src/variant.i"
	@echo "... src/variant.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

